### ISSUE TITLE
Ajuste inicial no repositório

### ISSUE THREAD

**Issue by RafyWP** [rafael-business/json-resume-wp#1]
Com o objetivo de deixar o repositório preparado para os trabalhos, solicito:

- [x] a remoção dos arquivos temporários de tradução .pot~ e .po~, e a inclusão destas terminações no arquivo .gitignore
- [x] verificação de versão e atualização, se necessário, dos assets utilizados em frontend, a saber, bootstrap e octicons
- [x] testar funcionamento e documentar o status inicial

**Comment by RafyWP** [comment]
Os assets são carregados nos arquivos de template, dentro da pasta templates. Favor não modificar este carregamento direto.

**Comment by sandroschutt** [comment]
# Esse relatório é relacionado ao primeiro e terceiro item listados na task


## Resumo dos testes
Instalar plugin e testar funcionalidades.

## Ambiente de teste
Descreva o ambiente no qual o plugin foi testado, incluindo:
- **Versão do WordPress:** 6.4.3
- **Tema:** Twenty Twenty Four 1.0.0
- **Versão do PHP:** 8.1.23
- **Ambiente do servidor:** nginx/1.16.0
- **Arquitetura do servidor:** Linux 5.15.0-100-generic x86_64
- **Navegador(es) usado(s):** Chrome, Firefox, Edge

## Testes de caso
#### Test Case: Instalação do plugin e teste de funcionalidades

**Descrição**: Verificar se a instalação do plugin apresenta problemas e erros

**Precondições**:
- Plugin não instalado.

**Passos**:
1. Clonar o plugin do repositório;
2. Adicionar o plugin à /wp-content/plugins;
3. Ativar o plugin pelo wp-admin ou wp-cli;
4. Inserir um objeto JSON no campo "JSON" da página do plugin ( [modelo](https://jsonresume.org/schema/) );
5. Clicar em "Salvar Alterações";
6. Recuperar o shortcode gerado;
7. Usar o shortcode em página ou post;

**Resultados esperados**:
- A ativação não é revertida após a gerar um erro;
- Adição de página ao wp-admin (ferramentas->JSON Resume);
- Geração de currículo a partir de objeto JSON;
- Geração e disponibilização de shortcode para o usuário;

**Recomendações**:
- Realizar a ativação do plugin em uma instalação limpa;
- Manter os arquivos de traducão .mo e .po;

## Resultados dos testes
#### Passaram:
- Ativação -  ocorre normalmente;
- Página no wp-admin - disponibiliza página no painel (ferramentas->JSON Resume);
- Shortcode - é gerado e registrado;
- Currículo - é inserido em posts e páginas através do shortcode;

#### Falharam:
- Shortcode -  não é disponibilizado para o usuário (precisei achá-lo com PHP);

## Conclusão

O plugin funciona corretamente, mas não disponibiliza o shortcode para o usuário, dificultando muito a obtenção do plugin por não desenvolvedores. É importante ressaltar que o plugin não funciona sem os arquivos de tradução:

- json-resume-wp-pt_BR.mo
- json-resume-wp-pt_BR.po


### Screenshots

#### Exibição do currículo em post:
![Image](https://github.com/rbz-digital/json-resume-wp/assets/68920430/b0a26fdb-f71e-4914-b85b-fa48db00ec2c)


#### Erro gerado ao remover os arquivos de tradução:
![Image](https://github.com/rbz-digital/json-resume-wp/assets/68920430/fd13a7fd-7dc4-4a00-8767-cfbbdfb8ce40)

**Comment by sandroschutt** [comment]
#### Atualização de CDNS:
- Bootstrap 5.2.0 > 5.3.3
- Octicon 4.4.0 > 8.5.0

**Comment by RafyWP** [comment]
@sandroschutt aqui era pra tirar só os arquivos temporários, os que tem o ~ na frente, tipo .pot~ e .po~
